spring:
  application:
    name: authenticationByExample
  security:
    user:
      name: kedar
      password: test1234

# To show default password on console when application started
# with basic spring security configuration
logging:
  level:
    org:
      springframework:
        security: INFO

server:
  servlet:
    session:
      persistent: false


